MockElasticSearchVouchersRequest1 = {
    "query": "Test Case 1",
    "from": 0,
    "per_page": 48,
    "order": None,
    "value": None,
    "store_names": [],
    "brand_names": [],
    "department_names": [],
    "category_names": [],
    "subcategory_names": [],
}
MockElasticSearchVouchersRequest2 = {
    "query": "Test Case 2",
    "from": 49,
    "per_page": 48,
    "order": None,
    "value": None,
    "store_names": [],
    "brand_names": [],
    "department_names": [],
    "category_names": [],
    "subcategory_names": [],
}
MockElasticSearchVouchersRequest3 = {
    "query": "Test Case 3",
    "from": 0,
    "per_page": 48,
    "order": None,
    "value": None,
    "store_names": [],
    "brand_names": ["Some brand"],
    "department_names": [],
    "category_names": [],
    "subcategory_names": [],
}
MockElasticSearchVouchersRequest4 = {
    "query": "Test Case 4",
    "from": 0,
    "per_page": 48,
    "order": None,
    "value": None,
    "store_names": [],
    "brand_names": [],
    "department_names": [],
    "category_names": ["Some Category"],
    "subcategory_names": [],
}
MockElasticSearchVouchersRequest5 = {
    "query": "Test Case 5",
    "from": 0,
    "per_page": 48,
    "order": None,
    "value": None,
    "store_names": [],
    "brand_names": [],
    "department_names": ["Some Department"],
    "category_names": [],
    "subcategory_names": [],
}
MockElasticSearchVouchersRequest6 = {
    "query": "Test Case 6",
    "from": 0,
    "per_page": 48,
    "order": None,
    "value": None,
    "store_names": [],
    "brand_names": [],
    "department_names": [],
    "category_names": [],
    "subcategory_names": ["Some Subcategory"],
}
