mock_query_input_01 = {
    "affinity": {
        "stores": [{"name": "Catch", "score": 1, "absolute": 34}],
        "brands": [{"name": "Nike", "score": 1, "absolute": 10}],
        "departments": [
            {"name": "Fashion", "score": 1, "absolute": 11},
        ],
        "categories": [
            {
                "name": "Phones, Smart Watches & Accessories",
                "score": 1,
                "absolute": 21,
            }
        ],
        "subcategories": [{"name": "Phones", "score": 1, "absolute": 11}],
    },
    "gender": "",
}

mock_query_input_02 = {
    "affinity": {},
    "store_names": ["Nike"],
    "brand_names": ["Nikon"],
    "department_names": ["Fashion"],
    "category_names": ["Computer Accessories & Network Hardware"],
    "subcategory_names": ["Computer"],
    "gender": "",
}

mock_query_input_03 = {
    "affinity": {},
    "gender": "Male",
}

mock_query_input_04 = {
    "affinity": {},
    "gender": "Female",
}

mock_search_elastic_response_01 = {
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "unknown query [funcrstrstrtion_score] did you mean [function_score]?",
                "line": 5,
                "col": 30,
            }
        ],
        "type": "parsing_exception",
        "reason": "unknown query [funcrstrstrtion_score] did you mean [function_score]?",
        "line": 5,
        "col": 30,
        "caused_by": {
            "type": "named_object_not_found_exception",
            "reason": "[5:30] unknown field [funcrstrstrtion_score]",
        },
    },
    "status": 400,
}

mock_search_elastic_response_02 = {
    "took": 6,
    "timed_out": False,
    "_shards": {"total": 3, "successful": 3, "skipped": 0, "failed": 0},
    "hits": {
        "total": {"value": 4, "relation": "eq"},
        "max_score": 1128.0,
        "hits": [
            {
                "_index": "sale_events_20230807",
                "_id": "296414",
                "_score": 1128.0,
                "_source": {
                    "category_boost_score": None,
                    "@timestamp": "2024-02-29T06:25:47.480Z",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296414/checkout/296414.jpg",
                    "slug": "30-off-womens-dresses-1709154230",
                    "is_top_sale_event": "true",
                    "operation": "u",
                    "description": "Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "url": "https://myer.sjv.io/c/2561188/1279730/15706?u=https%3A//www.myer.com.au/c/myer-one/myer-one-sale-women/women-clothing-myer-one/women-dresses-myer-one",
                    "brand_id": None,
                    "department_name": "Fashion",
                    "department_boost_score": None,
                    "downvotes_count": "0",
                    "store_logo": "https://media.littlebirdie.com.au/store/2_2023-06-15141715.204.jpg",
                    "category_id": "1462",
                    "store_boost_score": None,
                    "created_at": "2024-02-28T21:03:50.440Z",
                    "published_at": "2024-02-28T21:03:50.440Z",
                    "search_text": "30% off women's dresses 30-off-womens-dresses-1709154230 Women's Clothing Fashion Myer Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "brand_boost_score": None,
                    "@version": "1",
                    "followers_count": "0",
                    "sale_event_comments": "0",
                    "department_id": "94",
                    "click_through_count": "35",
                    "store_id": "2",
                    "sale_event_views": "93",
                    "cba_application_image": "Myer_Regatta2.jpg",
                    "category_name": "Women's Clothing",
                    "store_name": "Myer",
                    "object_properties": [
                        {
                            "category_name": "Women's Clothing",
                            "category_id": 1462,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "category_type": "primary",
                            "department_boost_score": 0,
                            "category_boost_score": 0,
                            "category_gender_affinity": "F",
                        }
                    ],
                    "datetime": "2024-02-29T06:25:47.124Z",
                    "id": "296414",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "sale_event_likes": "0",
                    "creator_type": None,
                    "state": "published",
                    "source_id": None,
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "name": "30% off women's dresses",
                    "impressions_count": "93",
                    "category_gender_affinity": "F",
                    "upvotes_count": "0",
                    "member_content": "false",
                    "user_id": "3",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296414/Copy_of_myer_dresses.jpg",
                    "comments_count": "0",
                    "start_at": "2024-02-28T15:00:00.000Z",
                    "brand_name": None,
                    "product_url": "https://www.myer.com.au/c/myer-one/myer-one-sale-women/women-clothing-myer-one/women-dresses-myer-one",
                    "availability": "",
                    "is_cba_exclusive": "false",
                    "coupon_code": None,
                    "offer_text": "30% off",
                    "creator_id": "3",
                    "expire_at": "2024-03-02T12:50:00.000Z",
                    "brand_logo": None,
                    "store_domain": "www.myer.com.au",
                    "updated_at": "2024-02-29T02:05:36.043Z",
                    "now": "2024-02-29T06:25:47.124Z",
                    "fixed_global_score": "1128",
                    "score": "1128",
                    "fixed_department_score": "1128",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
            {
                "_index": "sale_events_20230807",
                "_id": "296411",
                "_score": 1026.0,
                "_source": {
                    "url": "https://myer.sjv.io/c/2561188/1279730/15706?u=https%3A//www.myer.com.au/c/myer-one/myer-one-sale-home%3Ffacets%3Dmv--sale_type--502520off%26pageNumber%3D1%26promo_position%3DHomepage%257C3%257C2%257Ctile-master%26promo_id%3D2512f9cd-cd25-42fc-a8bd-cfaca512888c%26promo_creative%3DMaster__03__1x1.jpg%26promo_name%3D2024-02-23%257CAW24-HP-CONTENT%257CNon%2520promo%23filter-buttons",
                    "store_name": "Myer",
                    "state": "published",
                    "comments_count": "0",
                    "operation": "u",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "start_at": "2024-02-28T15:00:00.000Z",
                    "slug": "50-off-great-range-of-homewares-1709153921",
                    "brand_logo": None,
                    "sale_event_likes": "0",
                    "is_top_sale_event": "true",
                    "@timestamp": "2024-02-29T03:13:41.005Z",
                    "brand_boost_score": None,
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "store_boost_score": None,
                    "creator_type": None,
                    "is_cba_exclusive": "false",
                    "coupon_code": None,
                    "department_id": "86",
                    "click_through_count": "6",
                    "category_id": "1490",
                    "datetime": "2024-02-29T03:13:40.635Z",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296411/checkout/296411.jpg",
                    "brand_name": None,
                    "category_gender_affinity": None,
                    "source_id": None,
                    "impressions_count": "20",
                    "created_at": "2024-02-28T20:58:41.878Z",
                    "category_boost_score": None,
                    "store_logo": "https://media.littlebirdie.com.au/store/2_2023-06-15141715.204.jpg",
                    "store_id": "2",
                    "@version": "1",
                    "downvotes_count": "0",
                    "upvotes_count": "0",
                    "availability": "",
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "id": "296411",
                    "member_content": "false",
                    "user_id": "3",
                    "category_name": "Bedding",
                    "object_properties": [
                        {
                            "category_name": "Bedding",
                            "category_id": 1490,
                            "department_id": 86,
                            "department_type": "primary",
                            "department_name": "Home & Kitchen",
                            "category_type": "primary",
                            "department_boost_score": 0,
                            "category_boost_score": 0,
                            "category_gender_affinity": None,
                        },
                    ],
                    "search_text": "50% off great range of homewares 50-off-great-range-of-homewares-1709153921 Bedding Home & Kitchen Myer Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "offer_text": "50% off",
                    "cba_application_image": "Myer_Bed2.jpg",
                    "published_at": "2024-02-28T20:58:41.878Z",
                    "brand_id": None,
                    "product_url": "https://www.myer.com.au/c/myer-one/myer-one-sale-home?facets=mv--sale_type--502520off&pageNumber=1&promo_position=Homepage%7C3%7C2%7Ctile-master&promo_id=2512f9cd-cd25-42fc-a8bd-cfaca512888c&promo_creative=Master__03__1x1.jpg&promo_name=2024-02-23%7CAW24-HP-CONTENT%7CNon%20promo#filter-buttons",
                    "sale_event_comments": "0",
                    "name": "50% off great range of homewares",
                    "department_boost_score": None,
                    "updated_at": "2024-02-29T02:01:20.750Z",
                    "sale_event_views": "20",
                    "followers_count": "0",
                    "store_domain": "www.myer.com.au",
                    "creator_id": "3",
                    "expire_at": "2024-03-02T12:50:00.000Z",
                    "department_name": "Home & Kitchen",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296411/Copy_of_Master_Template-Black__48_.png",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "description": "Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "fixed_global_score": "1026",
                    "score": "1026",
                    "fixed_department_score": "1026",
                    "now": "2024-02-29T03:13:40.635Z",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
            {
                "_index": "sale_events_20230807",
                "_id": "296276",
                "_score": 1027.0,
                "_source": {
                    "store_name": "The Good Guys",
                    "state": "published",
                    "updated_at": "2024-02-28T02:36:09.368Z",
                    "category_name": "Audio & Headphones",
                    "availability": "",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296276/checkout/296276.jpg",
                    "member_content": "false",
                    "sale_event_comments": "0",
                    "datetime": "2024-02-29T00:53:47.044Z",
                    "sale_event_likes": "0",
                    "click_through_count": "5",
                    "followers_count": "0",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "store_logo": "https://media.littlebirdie.com.au/store/7_2022-12-02175011.073.jpg",
                    "slug": "15-off-huge-range-of-audio-1709069069",
                    "department_id": "89",
                    "creator_type": None,
                    "comments_count": "0",
                    "department_boost_score": None,
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "upvotes_count": "0",
                    "expire_at": "2024-03-01T12:50:00.000Z",
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "url": "https://prf.hn/click/camref:1011ljkyT/destination:https%3A//www.thegoodguys.com.au/buy/headphone-and-soundbar-sale%23facet%3A5750149533280114111109111116105111110484850",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "category_boost_score": None,
                    "store_id": "7",
                    "category_id": "1442",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296276/Copy_of_Master_Template-Black__46_.png",
                    "sale_event_views": "22",
                    "department_name": "Electronics",
                    "published_at": "2024-02-27T21:24:29.731Z",
                    "offer_text": "15% off",
                    "is_top_sale_event": "true",
                    "id": "296276",
                    "brand_name": None,
                    "created_at": "2024-02-27T21:24:29.731Z",
                    "object_properties": [
                        {
                            "category_name": "Audio & Headphones",
                            "category_id": 1442,
                            "department_type": "primary",
                            "department_id": 89,
                            "department_name": "Electronics",
                            "department_boost_score": 0,
                            "category_type": "primary",
                            "category_boost_score": 0,
                            "category_gender_affinity": None,
                        }
                    ],
                    "category_gender_affinity": None,
                    "description": "Discounts apply to previous ticketed/advertised price. As we negotiate, products will likely have been sold below ticketed/advertised price prior to the discount offer. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please reach out to us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "user_id": "3",
                    "brand_id": None,
                    "store_boost_score": None,
                    "name": "15% off huge range of audio",
                    "store_domain": "www.thegoodguys.com.au",
                    "search_text": "15% off huge range of audio 15-off-huge-range-of-audio-1709069069 Audio & Headphones Electronics The Good Guys Discounts apply to previous ticketed/advertised price. As we negotiate, products will likely have been sold below ticketed/advertised price prior to the discount offer. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please reach out to us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "brand_logo": None,
                    "@version": "1",
                    "start_at": "2024-02-27T15:00:00.000Z",
                    "coupon_code": None,
                    "is_cba_exclusive": "false",
                    "creator_id": "3",
                    "@timestamp": "2024-02-29T00:53:47.841Z",
                    "downvotes_count": "0",
                    "cba_application_image": "cba_image__36_.jpg",
                    "operation": "u",
                    "product_url": "https://www.thegoodguys.com.au/buy/headphone-and-soundbar-sale#facet:5750149533280114111109111116105111110484850",
                    "impressions_count": "22",
                    "brand_boost_score": None,
                    "source_id": None,
                    "fixed_global_score": "1027",
                    "score": "1027",
                    "fixed_department_score": "1027",
                    "now": "2024-02-29T00:53:47.044Z",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
            {
                "_index": "sale_events_20230807",
                "_id": "296412",
                "_score": 1017.0,
                "_source": {
                    "sale_event_comments": "0",
                    "brand_id": None,
                    "coupon_code": None,
                    "is_top_sale_event": "true",
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "source_id": None,
                    "department_name": "Fashion",
                    "state": "published",
                    "availability": "",
                    "followers_count": "0",
                    "downvotes_count": "0",
                    "start_at": "2024-02-28T15:00:00.000Z",
                    "offer_text": "20% off",
                    "click_through_count": "4",
                    "brand_name": None,
                    "operation": "u",
                    "member_content": "false",
                    "created_at": "2024-02-28T21:01:35.909Z",
                    "datetime": "2024-02-29T03:06:04.703Z",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "category_gender_affinity": "F",
                    "slug": "20-off-sports-top-picks-1709154095",
                    "updated_at": "2024-02-29T02:02:25.226Z",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296412/checkout/296412.jpg",
                    "is_cba_exclusive": "false",
                    "impressions_count": "13",
                    "comments_count": "0",
                    "category_name": "Women's Activewear",
                    "brand_logo": None,
                    "category_boost_score": None,
                    "object_properties": [
                        {
                            "category_name": "Women's Activewear",
                            "category_id": 1472,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "primary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "F",
                        },
                        {
                            "category_name": "Women's Clothing",
                            "category_id": 1462,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "secondary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "F",
                        },
                        {
                            "category_name": "Women's Shoes",
                            "category_id": 1471,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "secondary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "F",
                        },
                        {
                            "category_name": "Women's Accessories",
                            "category_id": 1458,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "secondary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "F",
                        },
                        {
                            "category_name": "Men's Accessories",
                            "category_id": 1467,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "secondary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "M",
                        },
                        {
                            "category_name": "Men's Activewear",
                            "category_id": 1468,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "secondary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "M",
                        },
                        {
                            "category_name": "Men's Clothing",
                            "category_id": 1469,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "department_boost_score": 0,
                            "category_type": "secondary",
                            "category_boost_score": 0,
                            "category_gender_affinity": "M",
                        },
                    ],
                    "@version": "1",
                    "description": "Selected styles and colours listed. Discount applied at checkout. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?.",
                    "creator_id": "3",
                    "id": "296412",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296412/Copy_of_Master_Template-Black__47_.png",
                    "cba_application_image": "The_Iconic-Activewear-CBA.jpg",
                    "search_text": "20% off sports top picks 20-off-sports-top-picks-1709154095 Women's Activewear Fashion The Iconic Selected styles and colours listed. Discount applied at checkout. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?.",
                    "user_id": "3",
                    "brand_boost_score": None,
                    "store_logo": "https://media.littlebirdie.com.au/store/17_2022-12-02114929.814.jpg",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "expire_at": "2024-03-05T12:50:00.000Z",
                    "sale_event_likes": "0",
                    "upvotes_count": "0",
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "store_id": "17",
                    "department_boost_score": None,
                    "name": "20% off sports top picks",
                    "store_boost_score": None,
                    "url": "https://prf.hn/click/camref:1011lfQEb/destination:https%3A//www.theiconic.com.au/womens-sports-all/%3Fcampaign%3Dlp-wmksbh-30-top-picks-0924-v2%26page%3D1%26sort%3Dpopularity",
                    "store_domain": "www.theiconic.com.au",
                    "sale_event_views": "13",
                    "creator_type": None,
                    "store_name": "The Iconic",
                    "product_url": "https://www.theiconic.com.au/womens-sports-all/?campaign=lp-wmksbh-30-top-picks-0924-v2&page=1&sort=popularity",
                    "@timestamp": "2024-02-29T03:06:05.575Z",
                    "department_id": "94",
                    "category_id": "1472",
                    "published_at": "2024-02-28T21:01:35.909Z",
                    "fixed_global_score": "1017",
                    "score": "1017",
                    "fixed_department_score": "1017",
                    "now": "2024-02-29T03:06:04.703Z",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
        ],
    },
}
mock_search_elastic_response_03 = {
    "took": 6,
    "timed_out": False,
    "_shards": {"total": 3, "successful": 3, "skipped": 0, "failed": 0},
    "hits": {
        "total": {"value": 24, "relation": "eq"},
        "max_score": 1128.0,
        "hits": [
            {
                "_index": "sale_events_20230807",
                "_id": "296414",
                "_score": 1128.0,
                "_source": {
                    "category_boost_score": None,
                    "@timestamp": "2024-02-29T06:25:47.480Z",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296414/checkout/296414.jpg",
                    "slug": "30-off-womens-dresses-1709154230",
                    "is_top_sale_event": "true",
                    "operation": "u",
                    "description": "Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "url": "https://myer.sjv.io/c/2561188/1279730/15706?u=https%3A//www.myer.com.au/c/myer-one/myer-one-sale-women/women-clothing-myer-one/women-dresses-myer-one",
                    "brand_id": None,
                    "department_name": "Fashion",
                    "department_boost_score": None,
                    "downvotes_count": "0",
                    "store_logo": "https://media.littlebirdie.com.au/store/2_2023-06-15141715.204.jpg",
                    "category_id": "1462",
                    "store_boost_score": None,
                    "created_at": "2024-02-28T21:03:50.440Z",
                    "published_at": "2024-02-28T21:03:50.440Z",
                    "search_text": "30% off women's dresses 30-off-womens-dresses-1709154230 Women's Clothing Fashion Myer Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "brand_boost_score": None,
                    "@version": "1",
                    "followers_count": "0",
                    "sale_event_comments": "0",
                    "department_id": "94",
                    "click_through_count": "35",
                    "store_id": "2",
                    "sale_event_views": "93",
                    "cba_application_image": "Myer_Regatta2.jpg",
                    "category_name": "Women's Clothing",
                    "store_name": "Myer",
                    "object_properties": [
                        {
                            "category_name": "Women's Clothing",
                            "category_id": 1462,
                            "department_id": 94,
                            "department_type": "primary",
                            "department_name": "Fashion",
                            "category_type": "primary",
                            "department_boost_score": 0,
                            "category_boost_score": 0,
                            "category_gender_affinity": "F",
                        }
                    ],
                    "datetime": "2024-02-29T06:25:47.124Z",
                    "id": "296414",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "sale_event_likes": "0",
                    "creator_type": None,
                    "state": "published",
                    "source_id": None,
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "name": "30% off women's dresses",
                    "impressions_count": "93",
                    "category_gender_affinity": "F",
                    "upvotes_count": "0",
                    "member_content": "false",
                    "user_id": "3",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296414/Copy_of_myer_dresses.jpg",
                    "comments_count": "0",
                    "start_at": "2024-02-28T15:00:00.000Z",
                    "brand_name": None,
                    "product_url": "https://www.myer.com.au/c/myer-one/myer-one-sale-women/women-clothing-myer-one/women-dresses-myer-one",
                    "availability": "",
                    "is_cba_exclusive": "false",
                    "coupon_code": None,
                    "offer_text": "30% off",
                    "creator_id": "3",
                    "expire_at": "2024-03-02T12:50:00.000Z",
                    "brand_logo": None,
                    "store_domain": "www.myer.com.au",
                    "updated_at": "2024-02-29T02:05:36.043Z",
                    "now": "2024-02-29T06:25:47.124Z",
                    "fixed_global_score": "1128",
                    "score": "1128",
                    "fixed_department_score": "1128",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
            {
                "_index": "sale_events_20230807",
                "_id": "296276",
                "_score": 1027.0,
                "_source": {
                    "store_name": "The Good Guys",
                    "state": "published",
                    "updated_at": "2024-02-28T02:36:09.368Z",
                    "category_name": "Audio & Headphones",
                    "availability": "",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296276/checkout/296276.jpg",
                    "member_content": "false",
                    "sale_event_comments": "0",
                    "datetime": "2024-02-29T00:53:47.044Z",
                    "sale_event_likes": "0",
                    "click_through_count": "5",
                    "followers_count": "0",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "store_logo": "https://media.littlebirdie.com.au/store/7_2022-12-02175011.073.jpg",
                    "slug": "15-off-huge-range-of-audio-1709069069",
                    "department_id": "89",
                    "creator_type": None,
                    "comments_count": "0",
                    "department_boost_score": None,
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "upvotes_count": "0",
                    "expire_at": "2024-03-01T12:50:00.000Z",
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "url": "https://prf.hn/click/camref:1011ljkyT/destination:https%3A//www.thegoodguys.com.au/buy/headphone-and-soundbar-sale%23facet%3A5750149533280114111109111116105111110484850",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "category_boost_score": None,
                    "store_id": "7",
                    "category_id": "1442",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296276/Copy_of_Master_Template-Black__46_.png",
                    "sale_event_views": "22",
                    "department_name": "Electronics",
                    "published_at": "2024-02-27T21:24:29.731Z",
                    "offer_text": "15% off",
                    "is_top_sale_event": "true",
                    "id": "296276",
                    "brand_name": None,
                    "created_at": "2024-02-27T21:24:29.731Z",
                    "object_properties": [
                        {
                            "category_name": "Audio & Headphones",
                            "category_id": 1442,
                            "department_type": "primary",
                            "department_id": 89,
                            "department_name": "Electronics",
                            "department_boost_score": 0,
                            "category_type": "primary",
                            "category_boost_score": 0,
                            "category_gender_affinity": None,
                        }
                    ],
                    "category_gender_affinity": None,
                    "description": "Discounts apply to previous ticketed/advertised price. As we negotiate, products will likely have been sold below ticketed/advertised price prior to the discount offer. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please reach out to us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "user_id": "3",
                    "brand_id": None,
                    "store_boost_score": None,
                    "name": "15% off huge range of audio",
                    "store_domain": "www.thegoodguys.com.au",
                    "search_text": "15% off huge range of audio 15-off-huge-range-of-audio-1709069069 Audio & Headphones Electronics The Good Guys Discounts apply to previous ticketed/advertised price. As we negotiate, products will likely have been sold below ticketed/advertised price prior to the discount offer. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please reach out to us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "brand_logo": None,
                    "@version": "1",
                    "start_at": "2024-02-27T15:00:00.000Z",
                    "coupon_code": None,
                    "is_cba_exclusive": "false",
                    "creator_id": "3",
                    "@timestamp": "2024-02-29T00:53:47.841Z",
                    "downvotes_count": "0",
                    "cba_application_image": "cba_image__36_.jpg",
                    "operation": "u",
                    "product_url": "https://www.thegoodguys.com.au/buy/headphone-and-soundbar-sale#facet:5750149533280114111109111116105111110484850",
                    "impressions_count": "22",
                    "brand_boost_score": None,
                    "source_id": None,
                    "fixed_global_score": "1027",
                    "score": "1027",
                    "fixed_department_score": "1027",
                    "now": "2024-02-29T00:53:47.044Z",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
            {
                "_index": "sale_events_20230807",
                "_id": "296411",
                "_score": 1026.0,
                "_source": {
                    "url": "https://myer.sjv.io/c/2561188/1279730/15706?u=https%3A//www.myer.com.au/c/myer-one/myer-one-sale-home%3Ffacets%3Dmv--sale_type--502520off%26pageNumber%3D1%26promo_position%3DHomepage%257C3%257C2%257Ctile-master%26promo_id%3D2512f9cd-cd25-42fc-a8bd-cfaca512888c%26promo_creative%3DMaster__03__1x1.jpg%26promo_name%3D2024-02-23%257CAW24-HP-CONTENT%257CNon%2520promo%23filter-buttons",
                    "store_name": "Myer",
                    "state": "published",
                    "comments_count": "0",
                    "operation": "u",
                    "source_last_checked_at": "1970-01-01T00:00:00.000Z",
                    "start_at": "2024-02-28T15:00:00.000Z",
                    "slug": "50-off-great-range-of-homewares-1709153921",
                    "brand_logo": None,
                    "sale_event_likes": "0",
                    "is_top_sale_event": "true",
                    "@timestamp": "2024-02-29T03:13:41.005Z",
                    "brand_boost_score": None,
                    "archived_at": "1970-01-01T00:00:00.000Z",
                    "store_boost_score": None,
                    "creator_type": None,
                    "is_cba_exclusive": "false",
                    "coupon_code": None,
                    "department_id": "86",
                    "click_through_count": "6",
                    "category_id": "1490",
                    "datetime": "2024-02-29T03:13:40.635Z",
                    "sale_event_image_checkout": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296411/checkout/296411.jpg",
                    "brand_name": None,
                    "category_gender_affinity": None,
                    "source_id": None,
                    "impressions_count": "20",
                    "created_at": "2024-02-28T20:58:41.878Z",
                    "category_boost_score": None,
                    "store_logo": "https://media.littlebirdie.com.au/store/2_2023-06-15141715.204.jpg",
                    "store_id": "2",
                    "@version": "1",
                    "downvotes_count": "0",
                    "upvotes_count": "0",
                    "availability": "",
                    "discarded_at": "1970-01-01T00:00:00.000Z",
                    "id": "296411",
                    "member_content": "false",
                    "user_id": "3",
                    "category_name": "Bedding",
                    "object_properties": [
                        {
                            "category_name": "Bedding",
                            "category_id": 1490,
                            "department_id": 86,
                            "department_type": "primary",
                            "department_name": "Home & Kitchen",
                            "category_type": "primary",
                            "department_boost_score": 0,
                            "category_boost_score": 0,
                            "category_gender_affinity": None,
                        },
                    ],
                    "search_text": "50% off great range of homewares 50-off-great-range-of-homewares-1709153921 Bedding Home & Kitchen Myer Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "offer_text": "50% off",
                    "cba_application_image": "Myer_Bed2.jpg",
                    "published_at": "2024-02-28T20:58:41.878Z",
                    "brand_id": None,
                    "product_url": "https://www.myer.com.au/c/myer-one/myer-one-sale-home?facets=mv--sale_type--502520off&pageNumber=1&promo_position=Homepage%7C3%7C2%7Ctile-master&promo_id=2512f9cd-cd25-42fc-a8bd-cfaca512888c&promo_creative=Master__03__1x1.jpg&promo_name=2024-02-23%7CAW24-HP-CONTENT%7CNon%20promo#filter-buttons",
                    "sale_event_comments": "0",
                    "name": "50% off great range of homewares",
                    "department_boost_score": None,
                    "updated_at": "2024-02-29T02:01:20.750Z",
                    "sale_event_views": "20",
                    "followers_count": "0",
                    "store_domain": "www.myer.com.au",
                    "creator_id": "3",
                    "expire_at": "2024-03-02T12:50:00.000Z",
                    "department_name": "Home & Kitchen",
                    "sale_event_image": "https://assets.littlebirdie.com.au/uploads/sale_event/sale_event_image/296411/Copy_of_Master_Template-Black__48_.png",
                    "rejected_at": "1970-01-01T00:00:00.000Z",
                    "description": "Myer one exclusive, sign up to shop. While stocks last. All prices shown are in Australian dollars (AUD). Further T&Cs may apply, please check the retailer's website for details. Sales are checked by Little Birdie staff to ensure accuracy, if you see something you believe is no longer accurate, please contact us by clicking Something wrong?. End date may change based on retailer requirements or promotions.",
                    "fixed_global_score": "1026",
                    "score": "1026",
                    "fixed_department_score": "1026",
                    "now": "2024-02-29T03:13:40.635Z",
                    "tags": ["valid_empty_ds"],
                    "brands": [{}],
                },
            },
        ],
    },
}
